name: Playwright CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            test-platform/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install root dependencies
        run: npm install

      - name: Install test-platform dependencies
        run: npm install --prefix test-platform

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:ci
        env:
          CI: true

      - name: Upload server log if exists
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: server-log
          path: test-platform/server.log
          if-no-files-found: ignore

      - name: Upload test results (Allure raw)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          if-no-files-found: ignore

      - name: Generate Allure Report
        if: always()
        run: |
          npm install -g allure-commandline || true
          sudo apt-get update && sudo apt-get install -y default-jre || true
          if [ -d allure-results ] && [ "$(ls -A allure-results)" ]; then
            allure generate allure-results --clean -o allure-report || true
          fi

      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          if-no-files-found: ignore

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

      - name: Upload traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: traces
          if-no-files-found: ignore

      - name: Download Allure HTML report
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report